import {
  Activity,
  Ambulance,
  Apple,
  Armchair,
  Baby,
  Bean,
  Bike,
  Bone,
  Brain,
  BrainCircuit,
  ClipboardPlus,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Egg,
  Eye,
  FlaskConical,
  Flower2,
  Footprints,
  HandHelping,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  Mars,
  MessagesSquare,
  Microscope,
  Ribbon,
  Salad,
  Scale,
  ScanFace,
  ScanLine,
  Scissors,
  Smile,
  SmilePlus,
  Sparkles,
  Stethoscope,
  Syringe,
  Venus,
  Waypoints,
  Wind,
  Workflow,
  type LucideProps,
} from "lucide-react";

/** Whitelist of icons a specialty may use (the name is stored in the database). */
const ICONS = {
  Activity,
  Ambulance,
  Apple,
  Armchair,
  Baby,
  Bean,
  Bike,
  Bone,
  Brain,
  BrainCircuit,
  ClipboardPlus,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Egg,
  Eye,
  FlaskConical,
  Flower2,
  Footprints,
  HandHelping,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  Mars,
  MessagesSquare,
  Microscope,
  Ribbon,
  Salad,
  Scale,
  ScanFace,
  ScanLine,
  Scissors,
  Smile,
  SmilePlus,
  Sparkles,
  Stethoscope,
  Syringe,
  Venus,
  Waypoints,
  Wind,
  Workflow,
} as const;

export const SPECIALTY_ICON_NAMES = Object.keys(ICONS);

export function SpecialtyIcon({ name, ...props }: { name: string } & LucideProps) {
  const Icon = ICONS[name as keyof typeof ICONS] ?? Stethoscope;
  return <Icon aria-hidden strokeWidth={1.75} {...props} />;
}
